name: Deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t mortiz33/client -f client/Dockerfile.dev ./client
      - run: docker build -t mortiz33/server -f server/Dockerfile.dev ./server
      - run: docker build -t mortiz33/nginx -f nginx/Dockerfile.dev ./nginx
      - run: docker build -t mortiz33/worker -f worker/Dockerfile.dev ./worker
      - run: docker push mortiz33/client
      - run: docker push mortiz33/server
      - run: docker push mortiz33/nginx
      - run: docker push mortiz33/worker

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: docker-multi-container-deployment
          environment_name: docker-multi-container-deployment-env
          existing_bucket_name: elasticbeanstalk-us-east-1-027576108866
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
